# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: execution.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'execution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65xecution.proto\x12\texecution\"A\n\x10\x45xecutionRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"C\n\x11\x45xecutionResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32`\n\x14\x43odeExecutionService\x12H\n\x0b\x45xecuteCode\x12\x1b.execution.ExecutionRequest\x1a\x1c.execution.ExecutionResponseB-\n\x19\x63om.project.codesync.grpcB\x0e\x45xecutionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'execution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.project.codesync.grpcB\016ExecutionProtoP\001'
  _globals['_EXECUTIONREQUEST']._serialized_start=30
  _globals['_EXECUTIONREQUEST']._serialized_end=95
  _globals['_EXECUTIONRESPONSE']._serialized_start=97
  _globals['_EXECUTIONRESPONSE']._serialized_end=164
  _globals['_CODEEXECUTIONSERVICE']._serialized_start=166
  _globals['_CODEEXECUTIONSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
